FROM python:3.10

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./scripts ./scripts
COPY ./src ./src

CMD ["python3", "scripts/run_app.py"]