FROM python:3.10

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi
ENV PYTHONPATH=/app


COPY ./scripts ./scripts
COPY ./src ./src
COPY ./db ./db

CMD python3 scripts/parsing_pipeline.py "$PROTOCOL"
