FROM python:3.10

WORKDIR /usr/src/app

ENV FLASK_ENV=production

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./api ./api
COPY ./db ./db

EXPOSE 3000

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:3000", "api"]
