FROM python:3.10

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./scripts ./scripts
COPY ./src ./src
COPY ./db ./db

CMD ["python3", "scripts/collect_raw_data.py"]