version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  db-init:
    build:
      dockerfile: ./Dockerfile.db-init
    environment:
      PG_CONNECTION_STRING: postgres://myuser:mypassword@db/postgres
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
