FROM python:3.10

WORKDIR /app
# Set PYTHONPATH to include /app so Python knows where to find your modules
ENV PYTHONPATH=/app

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./collection ./collection
COPY ./db ./db

CMD ["python3", "collection/tx_data/current_data_collector.py"]
