FROM python:3.10

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY ./collection ./collection
COPY ./db ./db

CMD ["python3", "collection/historical_signatures/signature_collector.py"]
