# docker compose is ment for local development, do not use docker compose in production!
version: '3.9'

services:
  # Postgres database
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    user: postgres 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  # api - reads from db, serves over http
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000

  # data-fetcher - fetches data and stores them in the database
  data-fetcher-signatures-mango:
    build:
      context: .
      dockerfile: Dockerfile.signature-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 60
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEY: 4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg
    depends_on:
      db:
        condition: service_healthy

  data-fetcher-signatures-solend:
    build:
      context: .
      dockerfile: Dockerfile.signature-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEY: So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo
    depends_on:
      db:
        condition: service_healthy

  data-fetcher-signatures-kamino:
    build:
      context: .
      dockerfile: Dockerfile.signature-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEY: KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD
    depends_on:
      db:
        condition: service_healthy

  data-fetcher-signatures-marginfi:
    build:
      context: .
      dockerfile: Dockerfile.signature-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEY: MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA
    depends_on:
      db:
        condition: service_healthy

  data-fetcher-current-tx-data:
    build:
      context: .
      dockerfile: Dockerfile.current-transactions-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEYS: KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD,So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo,4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg,MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA
    depends_on:
      db:
        condition: service_healthy

  data-fetcher-hist-tx-data:
    build:
      context: .
      dockerfile: Dockerfile.historical-transactions-collector
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      PROTOCOL_PUBLIC_KEYS: 6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc,So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo,4MangoMjqJ2firMokCjjGgoK8d4MXcrgL7XJaL3w6fVg
    depends_on:
      db:
        condition: service_healthy

  fe:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 20
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    ports:
      - 8501:8501

  # check locally that the database was initiated correctly
  # this component should not be in production
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ob-liq-fetcher:
    build:
      dockerfile: ./Dockerfile.ob-liq-fetching
    environment:
      AUTHENTICATED_RPC_URL: ""
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    depends_on:
      db:
        condition: service_healthy

  ts-fetcher:
    build:
      dockerfile: ./Dockerfile.ts-fetcher
    environment:
      AUTHENTICATED_RPC_URL: ""
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    depends_on:
      db:
        condition: service_healthy

  amm-liq-fetcher:
      build:
        dockerfile: ./Dockerfile.update-amm-pools
      environment:
        AUTHENTICATED_RPC_URL: ""
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  liquidity-normalizer:
      build:
        dockerfile: ./Dockerfile.liquidity-normalizer
      environment:
        AUTHENTICATED_RPC_URL: ""
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  token-supplies-fetcher:
      build:
        dockerfile: ./Dockerfile.token-supplies-fetching
      environment:
        AUTHENTICATED_RPC_URL: ""
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  marginfi-events-loan-state:
      build:
        dockerfile: ./Dockerfile.event_processing
      environment:
        PROTOCOL: marginfi
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  mango-events-loan-state:
      build:
        dockerfile: ./Dockerfile.event_processing
      environment:
        PROTOCOL: mango
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  kamino-events-loan-state:
      build:
        dockerfile: ./Dockerfile.event_processing
      environment:
        PROTOCOL: kamino
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: db
        POSTGRES_DB: postgres
      depends_on:
        db:
          condition: service_healthy

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
