# docker compose is ment for local development, do not use docker compose in production!
version: '3.9'

services:
  # Postgres database
  db:
    build:
      dockerfile: ./Dockerfile.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  # api - reads from db, serves over http
  api:
    build:
      dockerfile: ./Dockerfile.api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3000

  # data-fetcher - fetches data and stores them in the database
  data-fetcher:
    build:
      dockerfile: ./Dockerfile.raw-data-fetching
    environment:
      AUTHENTICATED_RPC_URL: https://<rpc_provider>/<api_token>
      RATE_LIMIT: 5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
    depends_on:
      db:
        condition: service_healthy

  fe:
    build:
      dockerfile: ./Dockerfile.frontend
    ports:
      - 8501:8501

  # check locally that the database was initiated correctly
  # this component should not be in production
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
