name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        run: |
          python3 -V
          python3 -m venv venv-solana
          source venv-solana/bin/activate
          pip install poetry
          poetry install
        shell: bash
      - name: Compress venv-solana
        run: |
          tar -czf venv-solana.tar.gz venv-solana

      - name: Upload venv-solana archive for test job
        uses: actions/upload-artifact@v2
        with:
          name: venv-solana-archive
          path: venv-solana.tar.gz


  test:
    needs: build
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - uses: actions/checkout@v2

      - name: Download venv-solana archive
        uses: actions/download-artifact@v2
        with:
          name: venv-solana-archive
          path: .

      - name: Decompress venv-solana archive
        run: |
          tar -xzf venv-solana.tar.gz
        shell: bash

      - name: Run tests
        run: |
          source venv-solana/bin/activate
          pip3 list
          PYTHONPATH=$PWD pytest tests/ -vv
        shell: bash
