name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        run: |
          python3 -V
          python3 -m venv venv-solana
          source venv-solana/bin/activate
          pip install poetry
          poetry install
        shell: bash
      - name: Upload venv-solana for test job
        uses: actions/upload-artifact@v2
        with:
          name: venv-solana
          path: venv-solana


  test:
    needs: build
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - uses: actions/checkout@v2

      - name: Download venv-solana from build job
        uses: actions/download-artifact@v2
        with:
          name: venv-solana
          path: venv-solana

      - name: Run tests
        run: |
          source venv-solana/bin/activate
          pip3 list
          PYTHONPATH=$PWD pytest tests/ -vv
        shell: bash
