name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          - python3 -V
          - python3 -m venv venv
          - source venv/bin/activate
          - poetry install

  test:
    needs: build
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Run tests
        run: PYTHONPATH=$PWD pytest tests/ -vv
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
